version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgresql_api_solid
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    volumes:
      - pg_data_api_solid:/bitnami/postgresql

volumes:
  pg_data_api_solid:
